build:
  image:
    name: contrun/website-template:latest
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1170
    entrypoint: [""]
  script:
    - set -xeu
    - find $PWD
    - HAKYLL_PROVIDER_DIRECTORY="$PWD" HAKYLL_DESTINATION_DIRECTORY="$PWD/public" make -C /hakyll/builder/
    - find $PWD
  except:
    - master

pages:
  image:
    name: contrun/website-template:latest
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1170
    entrypoint: [""]
  script:
    - set -xeu
    - find $PWD
    - HAKYLL_PROVIDER_DIRECTORY="$PWD" HAKYLL_DESTINATION_DIRECTORY="$PWD/public" make -C /hakyll/builder/
    - find $PWD
  artifacts:
    paths:
      - public
  only:
    - master
