build:
  image: contrun/website-template:latest
  before_script:
    - npm install
    - cabal update
    - cabal build
  script:
    - cabal exec site -- build
    - cabal exec site -- build
    - cabal exec site -- check
  except:
    - master

pages:
  image: contrun/website-template:latest
  before_script:
    - npm install
    - cabal update
    - cabal build
  script:
    - cabal exec site -- build
    - cabal exec site -- build
    - cabal exec site -- check
    - find .
  artifacts:
    paths:
      - public
  only:
    - master
