name: build docker image

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - main
      - actions
      - ci
      - 'releases/*'
  push:
    branches:
      - master
      - main
      - actions
      - ci
      - 'releases/*'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.10' ]

    steps:
    - uses: actions/checkout@v2

    - name: Get docker environment
      id: env
      run: |
        set -x
        [[ -z "$DOCKER_HUB_USERNAME" ]] && DOCKER_HUB_USERNAME="$(awk -F / '{print $1}' <<< "$GITHUB_REPOSITORY")"
        [[ -z "$PACKAGE_NAME" ]] && PACKAGE_NAME="$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        DOCKER_TAG="$(find cabal*.*.freeze *.cabal package*.json Dockerfile src | LC_ALL=C sort | cpio -o --quiet | sha512sum | cut -c 1-128)"
        DOCKER_HUB_URL="$DOCKER_HUB_USERNAME/$PACKAGE_NAME"
        DOCKER_IMAGE="$DOCKER_HUB_URL:$DOCKER_TAG"
        DOCKER_IMAGE_CACHE="$DOCKER_HUB_URL:cache"
        DOCKER_IMAGE_LATEST="$DOCKER_HUB_URL:latest"
        echo "::set-output name=DOCKER_HUB_USERNAME::$DOCKER_HUB_USERNAME"
        echo "::set-output name=DOCKER_IMAGE::$DOCKER_IMAGE"
        echo "::set-output name=DOCKER_IMAGE_LATEST::$DOCKER_IMAGE_LATEST"
        echo "::set-output name=DOCKER_IMAGE_CACHE::$DOCKER_IMAGE_CACHE"
        echo "::set-output name=DOCKER_TAGS::$DOCKER_IMAGE,$DOCKER_IMAGE_LATEST"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ steps.env.outputs.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.env.outputs.DOCKER_TAGS }}
        cache-from: ${{ steps.env.outputs.DOCKER_IMAGE_CACHE }}
        cache-to: ${{ steps.env.outputs.DOCKER_IMAGE_CACHE }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
