name: build hakyll website

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - main
      - actions
      - ci
      - 'releases/*'
  push:
    branches:
      - master
      - main
      - actions
      - ci
      - 'releases/*'

jobs:
  build-hakyll:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.10' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: actions/cache@v1
      name: Cache ~/.npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-version: 'latest'
        cabal-version: 'latest'
        ghc-version: ${{ matrix.ghc }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-
          cabal-store-${{ runner.OS }}-

    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-
          dist-newstyle-${{ runner.OS }}-

    - name: Cache stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: stack-work-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('*.cabal', 'stack.yaml*') }}
        restore-keys: |
          stack-work-${{ runner.OS }}-${{ matrix.ghc }}-
          stack-work-${{ runner.OS }}-

    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: home-stack-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('*.cabal', 'stack.yaml*') }}
        restore-keys: |
          home-stack-${{ runner.OS }}-${{ matrix.ghc }}-
          home-stack-${{ runner.OS }}-

    - name: Build the site
      env:
        LANG: en_US.UTF-8
      run: |
        HAKYLL_PROVIDER_DIRECTORY=. HAKYLL_DESTINATION_DIRECTORY=./public make

    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
