name: Hakyll site CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.10' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      name: Cache ~/.npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/setup-node@v1

    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-version: 'latest'
        cabal-version: 'latest'
        ghc-version: ${{ matrix.ghc }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-
          cabal-store-${{ runner.OS }}-

    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-
          dist-newstyle-${{ runner.OS }}-

    - name: Cache stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: stack-work-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('*.cabal', 'stack.yaml*') }}
        restore-keys: |
          stack-work-${{ runner.OS }}-${{ matrix.ghc }}-
          stack-work-${{ runner.OS }}-

    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: home-stack-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('*.cabal', 'stack.yaml*') }}
        restore-keys: |
          home-stack-${{ runner.OS }}-${{ matrix.ghc }}-
          home-stack-${{ runner.OS }}-

    - name: Build the site
      env:
        LANG: en_US.UTF-8
      run: |
        HAKYLL_PROVIDER_DIRECTORY=. HAKYLL_DESTINATION_DIRECTORY=./public make

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages

    - name: Build docker image, push it to docker hub
      run: |
        set -x
        [[ -z "$DOCKER_HUB_USERNAME" ]] && DOCKER_HUB_USERNAME="$(awk -F / '{print $1}' <<< "$GITHUB_REPOSITORY")"
        [[ -z "$PACKAGE_NAME" ]] && PACKAGE_NAME="$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        DOCKER_TAG="$(find .github/workflows .gitlab-ci.yml stack.yaml* *.cabal package*.json Dockerfile src | LC_ALL=C sort | cpio -o --quiet | sha512sum | cut -c 1-128)"
        DOCKER_HUB_URL="$DOCKER_HUB_USERNAME/$PACKAGE_NAME"
        DOCKER_IMAGE="$DOCKER_HUB_URL:$DOCKER_TAG"
        DOCKER_IMAGE_LATEST="$DOCKER_HUB_URL:latest"
        echo ${{secrets.DOCKER_HUB_TOKEN}} | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker pull "$DOCKER_IMAGE" && exit 0
        docker build -t "$DOCKER_IMAGE" .
        docker push "$DOCKER_IMAGE"
        docker build -t "$DOCKER_IMAGE_LATEST" .
        docker push "$DOCKER_IMAGE_LATEST"
