name: build hakyll website

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - main
      - actions
      - ci
      - 'releases/*'
  push:
    branches:
      - master
      - main
      - actions
      - ci
      - 'releases/*'

jobs:
  build-hakyll:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '9.8' ]

    steps:
    - uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ github.token }}
          substituters = https://cache.nixos.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Setup magic-nix-cache
      uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""

    - name: "Setup direnv"
      uses: JRMurr/direnv-nix-action@v4.1.0
      with:
        install-nix: "false"
        cache-store: "false"

    - uses: actions/cache@v1
      name: Cache ~/.npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-
          cabal-store-${{ runner.OS }}-

    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-
          dist-newstyle-${{ runner.OS }}-

    - name: Build the site
      env:
        LANG: en_US.UTF-8
      run: |
        HAKYLL_PROVIDER_DIRECTORY=. HAKYLL_DESTINATION_DIRECTORY=./public make

    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
